apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: prod

resources:
  # you can also specify a Git repo URL here
  - ../../base/
  
images:
  - name: cloud-native-weather-javaee
    newName: ghcr.io/qaware/cloud-native-weather-javaee
    newTag: 1.0.0

patchesStrategicMerge:
  - 2-replicas.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: weather-service
    path: loadbalancer.yaml
